## 1. Missing Values

### Step 1 – Understand the Concept
Own Words; Missing values mean some cells in the dataset do not contain useful data.

Definition: A missing value is a value that is absent or unavailable in a dataset.

Common representations: NaN, none,  NULL,  N/A, ""

We need to identify missing values before training an ML model.

### Step 2 – Real-World Analogy; 

Suppose a house record is: Area = 1500 sqft,  Bedrooms = 3,  Bathrooms = NaN,  Price = 85 lakhs

The bathroom information is missing.

A machine-learning model may not work correctly if missing values aren't handled properly.

### Step 3 – Implement in Python
Import libraries
import pandas as pd
import numpy as np

In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("house_price_prediction_50_rows_categorical_datetime.csv")

data.head()

,House_ ID,Area_sqft,Bedrooms,Bathrooms,Age_years,Location_Score,Parking_Spaces,Price_lakhs,Property_Type,Furnishing_Status,Construction_Status,Locality_Type,Listing_Date,Listing_Time
0,1,850.0,0.0,1,20.5,5,1.0,42,Apartment,Unfurnished,Ready to Move,Urban,1/5/2024,9:00:00
1,2,900.0,2.0,1,18.0,5,NaN,45,Independent House,Semi-Furnished,Under Construction,Suburban,1/23/2024,10:07:00
2,3,NaN,2.0,1,15.0,6,1.0,48,Villa,Fully Furnished,Ready to Move,Urban,2/10/2024,11:14:00
3,4,1000.9,2.0,2,12.0,6,1.0,52,Apartment,Semi-Furnished,Ready to Move,Suburban,2/28/2024,12:21:00
4,5,1050.0,2.0,2,10.0,6,1.0,55,Independent House,Unfurnished,Under Construction,Urban,3/17/2024,13:28:00

### Number of missing values

In [2]:
data.isnull().sum
len(data)

52

### Total missing values

In [3]:
data.isnull().sum().sum()

np.int64(5)

### Missing persentage values

In [4]:
Missing_Persentage = (data.isnull().sum() / len(data)) * 100

### Missing values by column

In [5]:
missing_report = pd.DataFrame({
    "Missing_Count" : data.isnull().sum(),
    "Missing_Percentage": (data.isnull().sum() / len(data)) * 100
})

print(missing_report)

                     Missing_Count  Missing_Percentage
House_ ID                        0            0.000000
Area_sqft                        1            1.923077
Bedrooms                         2            3.846154
Bathrooms                        0            0.000000
Age_years                        1            1.923077
Location_Score                   0            0.000000
Parking_Spaces                   1            1.923077
Price_lakhs                      0            0.000000
Property_Type                    0            0.000000
Furnishing_Status                0            0.000000
Construction_Status              0            0.000000
Locality_Type                    0            0.000000
Listing_Date                     0            0.000000
Listing_Time                     0            0.000000

### Missing values per row

In [6]:
data.isnull().sum(axis=1)

0     0
1     1
2     1
3     0
4     0
5     0
6     1
7     0
8     0
9     0
10    1
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    1
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
50    0
51    0
dtype: int64

## 3. Duplicate Records

### Step 1 – Understand the Concept
Own Words; Duplicate records mean the same house information appears more than once.

Definition; A duplicate record is a row that is identical to another row or is potentially representing the same entity.

### Step 2 – Real-World Analogy

Suppose we have:

Area = 1500
Bedrooms = 3
Bathrooms = 2
Price = 80

and exactly the same house record appears twice That is a duplicate.

### Step 3 – Implement in Python
Identify duplicates

In [7]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
dtype: bool

In [8]:
#count duplicates
data.duplicated().sum()

np.int64(0)

#### Display duplicate rows

In [9]:
data[data.duplicated()] #

Empty DataFrame
Columns: [House_ ID, Area_sqft, Bedrooms, Bathrooms, Age_years, Location_Score, Parking_Spaces, Price_lakhs, Property_Type, Furnishing_Status, Construction_Status, Locality_Type, Listing_Date, Listing_Time]
Index: []

#### Identify completely duplicated rows

In [10]:
data[data.duplicated(keep=False)]   ## keep=False displays both the original and duplicate records.

Empty DataFrame
Columns: [House_ ID, Area_sqft, Bedrooms, Bathrooms, Age_years, Location_Score, Parking_Spaces, Price_lakhs, Property_Type, Furnishing_Status, Construction_Status, Locality_Type, Listing_Date, Listing_Time]
Index: []

#### Identify potential duplicate records

In [11]:
# it menas may be few details same remaining different

In [12]:
## Invalid Values

### Step 1 – Understand the Concept
Own Words; Invalid values are values that don't make sense for the particular column.

Definition; An invalid value violates the expected range, meaning, format, or business rule of a variable.

### Step 2 – Real-World Analogy

A house cannot have:

Area = -1000 sqft
Bedrooms = -3
Price = -50 lakhs
Location Score = 25/10

These values are invalid.

### Step 3 – Implement in Python

First define numerical columns:

In [13]:
numeric_columns = [
    "Area_sqft",
    "Bedrooms",
    "Bathrooms",
    "Age_years",
    "Location_Score",
    "Parking_Spaces",
    "Price_lakhs"
]

In [14]:
null_like_values = [
    "",
    " ",
    "NULL",
    "null",
    "Null",
    "None",
    "none",
    "N/A",
    "n/a",
    "NA",
    "na",
    "?",
    "-",
    "Unknown",
    "unknown"
]

In [15]:
data_clean = data.copy()

In [16]:
data_clean = data_clean.replace(null_like_values,np.nan)

In [17]:
data_clean.isnull().sum()

House_ ID              0
Area_sqft              1
Bedrooms               2
Bathrooms              0
Age_years              1
Location_Score         1
Parking_Spaces         1
Price_lakhs            0
Property_Type          0
Furnishing_Status      0
Construction_Status    0
Locality_Type          0
Listing_Date           0
Listing_Time           0
dtype: int64

In [18]:
data.dtypes

House_ ID                int64
Area_sqft              float64
Bedrooms               float64
Bathrooms                int64
Age_years              float64
Location_Score          object
Parking_Spaces         float64
Price_lakhs              int64
Property_Type           object
Furnishing_Status       object
Construction_Status     object
Locality_Type           object
Listing_Date            object
Listing_Time            object
dtype: object

In [19]:
data_clean["Area_sqft"] = data_clean["Area_sqft"].fillna(
    data_clean["Area_sqft"].median()
)

In [20]:
data_clean["Bedrooms"] = data_clean["Bedrooms"].fillna(data_clean["Bedrooms"].median())

print(data_clean.head(50))

    House_ ID  Area_sqft  Bedrooms  Bathrooms  Age_years Location_Score  \
0           1      850.0       0.0          1       20.5              5
1           2      900.0       2.0          1       18.0              5
2           3     2150.0       2.0          1       15.0              6
3           4     1000.9       2.0          2       12.0              6
4           5     1050.0       2.0          2       10.0              6
5           6     1100.0       2.0          2        8.0              7
6           7     1150.5       4.0          2        7.0            NaN
7           8     1200.0       3.0          2        6.0              7
8           9     1250.0       3.0          2        5.0              8
9          10     1300.0       3.0          2        4.0              8
10         11     1350.0       3.0          2        NaN              6
11         12     1400.0       3.0          2       10.0              7
12         13     1450.0       3.0          2        8.0              7
13         14     1500.0       3.0          2        6.0              8
14         15     1550.0       3.0          2        5.0              8
15         16     1600.0       3.0          0        4.0              8
16         17     1650.0       3.0          3        3.0              9
17         18     1700.0       3.0          3        2.0              9
18         19     1750.0       3.0          3        1.0              9
19         20     1800.0       4.0          3        8.0              7
20         21     1850.0       3.0          3        7.0              8
21         22     1900.0       3.0          3        6.0              8
22         23     1950.0       3.0          3        5.0              9
23         24     2000.0       4.0          3        4.0              9
24         25     2050.0       4.0          3        3.0              9
25         26     2100.0       4.0          3        2.0             10
26         27     2150.0       4.0          3       10.0              7
27         28     2200.0       4.0          3        9.0              8
28         29     2250.0       4.0          3        8.0              8
29         30     2300.0       4.0          3        7.0              9
30         31     2350.0       4.0          3        6.0              9
31         32     2400.0       4.0          3        5.0              9
32         33     2450.0       4.0         -3        4.0             10
33         34     2500.0       4.0          3        3.0             10
34         35     2550.0       4.0          3        2.0             10
35         36     2600.0       4.0          3        1.0             10
36         37     2650.0       4.0          3       15.0              6
37         38     2700.0       4.0          3       12.0             -7
38         39     2750.0       4.0          3       10.0              8
39         40     2800.0       4.0          3        8.0              8
40         41     2850.0       4.0          3        6.0              9
41         42     2900.0       4.0          3        5.0              9
42         43     2950.0       4.0          4        4.0             10
43         44     3000.0       4.0          4        3.0             10
44         45     3100.0       4.0          4        2.0             10
45         46     3200.0       4.0          4        1.0             10
46         47     3300.0       5.0          4        7.0              9
47         48     3400.0       5.0          4        5.0              9
48         49     3500.0       5.0          4        3.0             10
49         50     3600.0       5.0          4        1.0             10

    Parking_Spaces  Price_lakhs      Property_Type Furnishing_Status  \
0              1.0           42          Apartment       Unfurnished
1              NaN           45  Independent House    Semi-Furnished
2              1.0           48              Villa   Fully Furnished
3              1.0           52          Apartment    Semi-Furnished
4              1.0           55  Independent House       Unfurnished
5              0.0           60          Apartment       Unfurnished
6              1.0           64  Independent House    Semi-Furnished
7              1.0           68              Villa   Fully Furnished
8              2.0           72          Apartment    Semi-Furnished
9              2.0           76  Independent House       Unfurnished
10             1.0           62          Apartment       Unfurnished
11             2.0           67  Independent House    Semi-Furnished
12             2.0           72              Villa   Fully Furnished
13             2.0           78          Apartment    Semi-Furnished
14             2.0           83  Independent House       Unfurnished
15             2.0           88          Apartment       Unfurnished
16             2.0           96  Independent House    Semi-Furnished
17             2.0          102              Villa   Fully Furnished
18             2.0          110          Apartment    Semi-Furnished
19             2.0           92  Independent House       Unfurnished
20             2.0           98          Apartment       Unfurnished
21             2.0          105  Independent House    Semi-Furnished
22             2.0          112              Villa   Fully Furnished
23             2.0          125          Apartment    Semi-Furnished
24             2.0          132  Independent House       Unfurnished
25             2.0          140          Apartment       Unfurnished
26             2.0          118  Independent House    Semi-Furnished
27             2.0          126              Villa   Fully Furnished
28             2.0          134          Apartment    Semi-Furnished
29             2.0          143  Independent House       Unfurnished
30             2.0          151          Apartment       Unfurnished
31             2.0          160  Independent House    Semi-Furnished
32             2.0          170              Villa   Fully Furnished
33             2.0          180          Apartment    Semi-Furnished
34             2.0          190  Independent House       Unfurnished
35             2.0          202          Apartment       Unfurnished
36             2.0          145  Independent House    Semi-Furnished
37             2.0          155              Villa   Fully Furnished
38             2.0          166          Apartment    Semi-Furnished
39             2.0          178  Independent House       Unfurnished
40             2.0          190          Apartment       Unfurnished
41             2.0          203  Independent House    Semi-Furnished
42             2.0          218              Villa   Fully Furnished
43             2.0          232          Apartment    Semi-Furnished
44             3.0         -250  Independent House       Unfurnished
45             3.0          270          Apartment       Unfurnished
46             3.0          285  Independent House    Semi-Furnished
47             3.0          305              Villa   Fully Furnished
48             3.0          330          Apartment    Semi-Furnished
49             3.0          355  Independent House       Unfurnished

   Construction_Status Locality_Type Listing_Date Listing_Time
0        Ready to Move         Urban     1/5/2024      9:00:00
1   Under Construction      Suburban    1/23/2024     10:07:00
2        Ready to Move         Urban    2/10/2024     11:14:00
3        Ready to Move      Suburban    2/28/2024     12:21:00
4   Under Construction         Urban    3/17/2024     13:28:00
5        Ready to Move         Urban     4/4/2024     14:35:00
6   Under Construction      Suburban    4/22/2024     15:42:00
7        Ready to Move         Urban    5/10/2024     16:49:00
8        Ready to Move      Suburban    5/28/2024     17:56:00
9   Under Construction         Urban    6/15/2024      9:03:00
10       Ready to Move         Urban     7/3/2024     10:10:00
11  Under Construction      Suburban    7/21/2024     11:17:00
12       Ready to Move         Urban     8/8/2024     12:24:00
13       Ready to Move      Suburban    8/26/2024     13:31:00
14  Under Construction         Urban    9/13/2024     14:38:00
15       Ready to Move         Urban    10/1/2024     15:45:00
16  Under Construction      Suburban   10/19/2024     16:52:00
17       Ready to Move         Urban    11/6/2024     17:59:00
18       Ready to Move      Suburban   11/24/2024      9:06:00
19  Under Construction         Urban   12/12/2024     10:13:00
20       Ready to Move         Urban   12/30/2024     11:20:00
21  Under Construction      Suburban    1/17/2025     12:27:00
22       Ready to Move         Urban     2/4/2025     13:34:00
23       Ready to Move      Suburban    2/22/2025     14:41:00
24  Under Construction         Urban    3/12/2025     15:48:00
25       Ready to Move         Urban    3/30/2025     16:55:00
26  Under Construction      Suburban    4/17/2025     17:02:00
27       Ready to Move         Urban     5/5/2025      9:09:00
28       Ready to Move      Suburban    5/23/2025     10:16:00
29  Under Construction         Urban    6/10/2025     11:23:00
30       Ready to Move         Urban    6/28/2025     12:30:00
31  Under Construction      Suburban    7/16/2025     13:37:00
32       Ready to Move         Urban     8/3/2025     14:44:00
33       Ready to Move      Suburban    8/21/2025     15:51:00
34  Under Construction         Urban     9/8/2025     16:58:00
35       Ready to Move         Urban    9/26/2025     17:05:00
36  Under Construction      Suburban   10/14/2025      9:12:00
37       Ready to Move         Urban    11/1/2025     10:19:00
38       Ready to Move      Suburban   11/19/2025     11:26:00
39  Under Construction         Urban    12/7/2025     12:33:00
40       Ready to Move         Urban   12/25/2025     13:40:00
41  Under Construction      Suburban    1/12/2026     14:47:00
42       Ready to Move         Urban    1/30/2026     15:54:00
43       Ready to Move      Suburban    2/17/2026     16:01:00
44  Under Construction         Urban     3/7/2026     17:08:00
45       Ready to Move         Urban    3/25/2026      9:15:00
46  Under Construction      Suburban    4/12/2026     10:22:00
47       Ready to Move         Urban    4/30/2026     11:29:00
48       Ready to Move      Suburban    5/18/2026     12:36:00
49  Under Construction         Urban     6/5/2026     13:43:00

In [21]:
data_clean["Age_years"] = data_clean["Age_years"].fillna(data_clean["Age_years"].median())
data_clean["Parking_Spaces"] = data_clean["Parking_Spaces"].fillna(data_clean["Parking_Spaces"].median())

print(data_clean.head(50))

    House_ ID  Area_sqft  Bedrooms  Bathrooms  Age_years Location_Score  \
0           1      850.0       0.0          1       20.5              5
1           2      900.0       2.0          1       18.0              5
2           3     2150.0       2.0          1       15.0              6
3           4     1000.9       2.0          2       12.0              6
4           5     1050.0       2.0          2       10.0              6
5           6     1100.0       2.0          2        8.0              7
6           7     1150.5       4.0          2        7.0            NaN
7           8     1200.0       3.0          2        6.0              7
8           9     1250.0       3.0          2        5.0              8
9          10     1300.0       3.0          2        4.0              8
10         11     1350.0       3.0          2        6.0              6
11         12     1400.0       3.0          2       10.0              7
12         13     1450.0       3.0          2        8.0              7
13         14     1500.0       3.0          2        6.0              8
14         15     1550.0       3.0          2        5.0              8
15         16     1600.0       3.0          0        4.0              8
16         17     1650.0       3.0          3        3.0              9
17         18     1700.0       3.0          3        2.0              9
18         19     1750.0       3.0          3        1.0              9
19         20     1800.0       4.0          3        8.0              7
20         21     1850.0       3.0          3        7.0              8
21         22     1900.0       3.0          3        6.0              8
22         23     1950.0       3.0          3        5.0              9
23         24     2000.0       4.0          3        4.0              9
24         25     2050.0       4.0          3        3.0              9
25         26     2100.0       4.0          3        2.0             10
26         27     2150.0       4.0          3       10.0              7
27         28     2200.0       4.0          3        9.0              8
28         29     2250.0       4.0          3        8.0              8
29         30     2300.0       4.0          3        7.0              9
30         31     2350.0       4.0          3        6.0              9
31         32     2400.0       4.0          3        5.0              9
32         33     2450.0       4.0         -3        4.0             10
33         34     2500.0       4.0          3        3.0             10
34         35     2550.0       4.0          3        2.0             10
35         36     2600.0       4.0          3        1.0             10
36         37     2650.0       4.0          3       15.0              6
37         38     2700.0       4.0          3       12.0             -7
38         39     2750.0       4.0          3       10.0              8
39         40     2800.0       4.0          3        8.0              8
40         41     2850.0       4.0          3        6.0              9
41         42     2900.0       4.0          3        5.0              9
42         43     2950.0       4.0          4        4.0             10
43         44     3000.0       4.0          4        3.0             10
44         45     3100.0       4.0          4        2.0             10
45         46     3200.0       4.0          4        1.0             10
46         47     3300.0       5.0          4        7.0              9
47         48     3400.0       5.0          4        5.0              9
48         49     3500.0       5.0          4        3.0             10
49         50     3600.0       5.0          4        1.0             10

    Parking_Spaces  Price_lakhs      Property_Type Furnishing_Status  \
0              1.0           42          Apartment       Unfurnished
1              2.0           45  Independent House    Semi-Furnished
2              1.0           48              Villa   Fully Furnished
3              1.0           52          Apartment    Semi-Furnished
4              1.0           55  Independent House       Unfurnished
5              0.0           60          Apartment       Unfurnished
6              1.0           64  Independent House    Semi-Furnished
7              1.0           68              Villa   Fully Furnished
8              2.0           72          Apartment    Semi-Furnished
9              2.0           76  Independent House       Unfurnished
10             1.0           62          Apartment       Unfurnished
11             2.0           67  Independent House    Semi-Furnished
12             2.0           72              Villa   Fully Furnished
13             2.0           78          Apartment    Semi-Furnished
14             2.0           83  Independent House       Unfurnished
15             2.0           88          Apartment       Unfurnished
16             2.0           96  Independent House    Semi-Furnished
17             2.0          102              Villa   Fully Furnished
18             2.0          110          Apartment    Semi-Furnished
19             2.0           92  Independent House       Unfurnished
20             2.0           98          Apartment       Unfurnished
21             2.0          105  Independent House    Semi-Furnished
22             2.0          112              Villa   Fully Furnished
23             2.0          125          Apartment    Semi-Furnished
24             2.0          132  Independent House       Unfurnished
25             2.0          140          Apartment       Unfurnished
26             2.0          118  Independent House    Semi-Furnished
27             2.0          126              Villa   Fully Furnished
28             2.0          134          Apartment    Semi-Furnished
29             2.0          143  Independent House       Unfurnished
30             2.0          151          Apartment       Unfurnished
31             2.0          160  Independent House    Semi-Furnished
32             2.0          170              Villa   Fully Furnished
33             2.0          180          Apartment    Semi-Furnished
34             2.0          190  Independent House       Unfurnished
35             2.0          202          Apartment       Unfurnished
36             2.0          145  Independent House    Semi-Furnished
37             2.0          155              Villa   Fully Furnished
38             2.0          166          Apartment    Semi-Furnished
39             2.0          178  Independent House       Unfurnished
40             2.0          190          Apartment       Unfurnished
41             2.0          203  Independent House    Semi-Furnished
42             2.0          218              Villa   Fully Furnished
43             2.0          232          Apartment    Semi-Furnished
44             3.0         -250  Independent House       Unfurnished
45             3.0          270          Apartment       Unfurnished
46             3.0          285  Independent House    Semi-Furnished
47             3.0          305              Villa   Fully Furnished
48             3.0          330          Apartment    Semi-Furnished
49             3.0          355  Independent House       Unfurnished

   Construction_Status Locality_Type Listing_Date Listing_Time
0        Ready to Move         Urban     1/5/2024      9:00:00
1   Under Construction      Suburban    1/23/2024     10:07:00
2        Ready to Move         Urban    2/10/2024     11:14:00
3        Ready to Move      Suburban    2/28/2024     12:21:00
4   Under Construction         Urban    3/17/2024     13:28:00
5        Ready to Move         Urban     4/4/2024     14:35:00
6   Under Construction      Suburban    4/22/2024     15:42:00
7        Ready to Move         Urban    5/10/2024     16:49:00
8        Ready to Move      Suburban    5/28/2024     17:56:00
9   Under Construction         Urban    6/15/2024      9:03:00
10       Ready to Move         Urban     7/3/2024     10:10:00
11  Under Construction      Suburban    7/21/2024     11:17:00
12       Ready to Move         Urban     8/8/2024     12:24:00
13       Ready to Move      Suburban    8/26/2024     13:31:00
14  Under Construction         Urban    9/13/2024     14:38:00
15       Ready to Move         Urban    10/1/2024     15:45:00
16  Under Construction      Suburban   10/19/2024     16:52:00
17       Ready to Move         Urban    11/6/2024     17:59:00
18       Ready to Move      Suburban   11/24/2024      9:06:00
19  Under Construction         Urban   12/12/2024     10:13:00
20       Ready to Move         Urban   12/30/2024     11:20:00
21  Under Construction      Suburban    1/17/2025     12:27:00
22       Ready to Move         Urban     2/4/2025     13:34:00
23       Ready to Move      Suburban    2/22/2025     14:41:00
24  Under Construction         Urban    3/12/2025     15:48:00
25       Ready to Move         Urban    3/30/2025     16:55:00
26  Under Construction      Suburban    4/17/2025     17:02:00
27       Ready to Move         Urban     5/5/2025      9:09:00
28       Ready to Move      Suburban    5/23/2025     10:16:00
29  Under Construction         Urban    6/10/2025     11:23:00
30       Ready to Move         Urban    6/28/2025     12:30:00
31  Under Construction      Suburban    7/16/2025     13:37:00
32       Ready to Move         Urban     8/3/2025     14:44:00
33       Ready to Move      Suburban    8/21/2025     15:51:00
34  Under Construction         Urban     9/8/2025     16:58:00
35       Ready to Move         Urban    9/26/2025     17:05:00
36  Under Construction      Suburban   10/14/2025      9:12:00
37       Ready to Move         Urban    11/1/2025     10:19:00
38       Ready to Move      Suburban   11/19/2025     11:26:00
39  Under Construction         Urban    12/7/2025     12:33:00
40       Ready to Move         Urban   12/25/2025     13:40:00
41  Under Construction      Suburban    1/12/2026     14:47:00
42       Ready to Move         Urban    1/30/2026     15:54:00
43       Ready to Move      Suburban    2/17/2026     16:01:00
44  Under Construction         Urban     3/7/2026     17:08:00
45       Ready to Move         Urban    3/25/2026      9:15:00
46  Under Construction      Suburban    4/12/2026     10:22:00
47       Ready to Move         Urban    4/30/2026     11:29:00
48       Ready to Move      Suburban    5/18/2026     12:36:00
49  Under Construction         Urban     6/5/2026     13:43:00

## Handle Negative values to positive

In [22]:
data_clean["Location_Score"] = pd.to_numeric(data_clean["Location_Score"], errors="coerce")

In [23]:
## _ values comverting to nan and median aslo
data_clean.loc[data_clean["Location_Score"] <= 0, "Location_Score"] = np.nan
data_clean.loc[data_clean["Bedrooms"] <= 0, "Bedrooms"] = np.nan

data_clean["Location_Score"] = data_clean["Location_Score"].fillna(data_clean["Location_Score"].median())

In [51]:
# converting _ values and 0 values into NAN
data_clean.loc[data_clean["Price_lakhs"] <=0, "Price_lakhs"] = np.nan
data_clean.loc[data_clean["Parking_Spaces"] <=0, "Parking_Spaces"] = np.nan
data_clean.loc[data_clean["Bathrooms"] <=0, "Bathrooms"] = np.nan

In [53]:
## multiple columns converting NAN to median
multiple_col = ["Area_sqft", "Bedrooms", "Bathrooms", "Parking_Spaces", "Price_lakhs"]

for col in multiple_col:
    data_clean[col] = data_clean[col].fillna(data_clean[col].median())

In [54]:
print(data_clean.head(50))

    House_ ID  Area_sqft  Bedrooms  Bathrooms  Age_years  Location_Score  \
0           1      850.0       4.0        1.0       20.5             5.0
1           2      900.0       2.0        1.0       18.0             5.0
2           3     2150.0       2.0        1.0       15.0             6.0
3           4     1000.9       2.0        2.0       12.0             6.0
4           5     1050.0       2.0        2.0       10.0             6.0
5           6     1100.0       2.0        2.0        8.0             7.0
6           7     1150.5       4.0        2.0        7.0             8.0
7           8     1200.0       3.0        2.0        6.0             7.0
8           9     1250.0       3.0        2.0        5.0             8.0
9          10     1300.0       3.0        2.0        4.0             8.0
10         11     1350.0       3.0        2.0        6.0             6.0
11         12     1400.0       3.0        2.0       10.0             7.0
12         13     1450.0       3.0        2.0        8.0             7.0
13         14     1500.0       3.0        2.0        6.0             8.0
14         15     1550.0       3.0        2.0        5.0             8.0
15         16     1600.0       3.0        3.0        4.0             8.0
16         17     1650.0       3.0        3.0        3.0             9.0
17         18     1700.0       3.0        3.0        2.0             9.0
18         19     1750.0       3.0        3.0        1.0             9.0
19         20     1800.0       4.0        3.0        8.0             7.0
20         21     1850.0       3.0        3.0        7.0             8.0
21         22     1900.0       3.0        3.0        6.0             8.0
22         23     1950.0       3.0        3.0        5.0             9.0
23         24     2000.0       4.0        3.0        4.0             9.0
24         25     2050.0       4.0        3.0        3.0             9.0
25         26     2100.0       4.0        3.0        2.0            10.0
26         27     2150.0       4.0        3.0       10.0             7.0
27         28     2200.0       4.0        3.0        9.0             8.0
28         29     2250.0       4.0        3.0        8.0             8.0
29         30     2300.0       4.0        3.0        7.0             9.0
30         31     2350.0       4.0        3.0        6.0             9.0
31         32     2400.0       4.0        3.0        5.0             9.0
32         33     2450.0       4.0        3.0        4.0            10.0
33         34     2500.0       4.0        3.0        3.0            10.0
34         35     2550.0       4.0        3.0        2.0            10.0
35         36     2600.0       4.0        3.0        1.0            10.0
36         37     2650.0       4.0        3.0       15.0             6.0
37         38     2700.0       4.0        3.0       12.0             8.0
38         39     2750.0       4.0        3.0       10.0             8.0
39         40     2800.0       4.0        3.0        8.0             8.0
40         41     2850.0       4.0        3.0        6.0             9.0
41         42     2900.0       4.0        3.0        5.0             9.0
42         43     2950.0       4.0        4.0        4.0            10.0
43         44     3000.0       4.0        4.0        3.0            10.0
44         45     3100.0       4.0        4.0        2.0            10.0
45         46     3200.0       4.0        4.0        1.0            10.0
46         47     3300.0       5.0        4.0        7.0             9.0
47         48     3400.0       5.0        4.0        5.0             9.0
48         49     3500.0       5.0        4.0        3.0            10.0
49         50     3600.0       5.0        4.0        1.0            10.0

    Parking_Spaces  Price_lakhs      Property_Type Furnishing_Status  \
0              1.0         42.0          Apartment       Unfurnished
1              2.0         45.0  Independent House    Semi-Furnished
2              1.0         48.0              Villa   Fully Furnished
3              1.0         52.0          Apartment    Semi-Furnished
4              1.0         55.0  Independent House       Unfurnished
5              2.0         60.0          Apartment       Unfurnished
6              1.0         64.0  Independent House    Semi-Furnished
7              1.0         68.0              Villa   Fully Furnished
8              2.0         72.0          Apartment    Semi-Furnished
9              2.0         76.0  Independent House       Unfurnished
10             1.0         62.0          Apartment       Unfurnished
11             2.0         67.0  Independent House    Semi-Furnished
12             2.0         72.0              Villa   Fully Furnished
13             2.0         78.0          Apartment    Semi-Furnished
14             2.0         83.0  Independent House       Unfurnished
15             2.0         88.0          Apartment       Unfurnished
16             2.0         96.0  Independent House    Semi-Furnished
17             2.0        102.0              Villa   Fully Furnished
18             2.0        110.0          Apartment    Semi-Furnished
19             2.0         92.0  Independent House       Unfurnished
20             2.0         98.0          Apartment       Unfurnished
21             2.0        105.0  Independent House    Semi-Furnished
22             2.0        112.0              Villa   Fully Furnished
23             2.0        125.0          Apartment    Semi-Furnished
24             2.0        132.0  Independent House       Unfurnished
25             2.0        140.0          Apartment       Unfurnished
26             2.0        118.0  Independent House    Semi-Furnished
27             2.0        126.0              Villa   Fully Furnished
28             2.0        134.0          Apartment    Semi-Furnished
29             2.0        143.0  Independent House       Unfurnished
30             2.0        151.0          Apartment       Unfurnished
31             2.0        160.0  Independent House    Semi-Furnished
32             2.0        170.0              Villa   Fully Furnished
33             2.0        180.0          Apartment    Semi-Furnished
34             2.0        190.0  Independent House       Unfurnished
35             2.0        202.0          Apartment       Unfurnished
36             2.0        145.0  Independent House    Semi-Furnished
37             2.0        155.0              Villa   Fully Furnished
38             2.0        166.0          Apartment    Semi-Furnished
39             2.0        178.0  Independent House       Unfurnished
40             2.0        190.0          Apartment       Unfurnished
41             2.0        203.0  Independent House    Semi-Furnished
42             2.0        218.0              Villa   Fully Furnished
43             2.0        232.0          Apartment    Semi-Furnished
44             3.0        125.0  Independent House       Unfurnished
45             3.0        270.0          Apartment       Unfurnished
46             3.0        285.0  Independent House    Semi-Furnished
47             3.0        305.0              Villa   Fully Furnished
48             3.0        330.0          Apartment    Semi-Furnished
49             3.0        355.0  Independent House       Unfurnished

   Construction_Status Locality_Type
0        Ready to Move         Urban
1   Under Construction      Suburban
2        Ready to Move         Urban
3        Ready to Move      Suburban
4   Under Construction         Urban
5        Ready to Move         Urban
6   Under Construction      Suburban
7        Ready to Move         Urban
8        Ready to Move      Suburban
9   Under Construction         Urban
10       Ready to Move         Urban
11  Under Construction      Suburban
12       Ready to Move         Urban
13       Ready to Move      Suburban
14  Under Construction         Urban
15       Ready to Move         Urban
16  Under Construction      Suburban
17       Ready to Move         Urban
18       Ready to Move      Suburban
19  Under Construction         Urban
20       Ready to Move         Urban
21  Under Construction      Suburban
22       Ready to Move         Urban
23       Ready to Move      Suburban
24  Under Construction         Urban
25       Ready to Move         Urban
26  Under Construction      Suburban
27       Ready to Move         Urban
28       Ready to Move      Suburban
29  Under Construction         Urban
30       Ready to Move         Urban
31  Under Construction      Suburban
32       Ready to Move         Urban
33       Ready to Move      Suburban
34  Under Construction         Urban
35       Ready to Move         Urban
36  Under Construction      Suburban
37       Ready to Move         Urban
38       Ready to Move      Suburban
39  Under Construction         Urban
40       Ready to Move         Urban
41  Under Construction      Suburban
42       Ready to Move         Urban
43       Ready to Move      Suburban
44  Under Construction         Urban
45       Ready to Move         Urban
46  Under Construction      Suburban
47       Ready to Move         Urban
48       Ready to Move      Suburban
49  Under Construction         Urban

## 8. Incorrect Categories

In [27]:
categorical_columns = [
    "Property_Type",
    "Furnishing_Status",
    "Construction_Status",
    "Locality_Type"
]

### Step 1 – Understand the Concept
Own Words;  Categorical columns contain labels rather than numerical measurements.

Definition;  Categorical variables represent groups or categories.

### Step 2 – Real-World Analogy

For Property_Type: Apartment, Villa, Independent House

If the dataset contains:

Apartment
Villa
Mansion

and Mansion wasn't an allowed category, it is an unexpected category.

### Step 3 – Implement in Python

In [28]:
for column in categorical_columns:
    print(column)
    print(data[column].unique())

Property_Type
['Apartment' 'Independent House' 'Villa']
Furnishing_Status
['Unfurnished' 'Semi-Furnished' 'Fully Furnished']
Construction_Status
['Ready to Move' 'Under Construction']
Locality_Type
['Urban' 'Suburban']

In [29]:
categorical_columns = [
    "Property_Type",
    "Furnishing_Status",
    "Construction_Status",
    "Locality_Type"
]

# validate property_type

In [30]:
validate_property_type = ["Apartment","Independent House", "Villa"]

data[data["Property_Type"].isin(validate_property_type)]

,House_ ID,Area_sqft,Bedrooms,Bathrooms,Age_years,Location_Score,Parking_Spaces,Price_lakhs,Property_Type,Furnishing_Status,Construction_Status,Locality_Type,Listing_Date,Listing_Time
0,1,850.0,0.0,1,20.5,5,1.0,42,Apartment,Unfurnished,Ready to Move,Urban,1/5/2024,9:00:00
1,2,900.0,2.0,1,18.0,5,NaN,45,Independent House,Semi-Furnished,Under Construction,Suburban,1/23/2024,10:07:00
2,3,NaN,2.0,1,15.0,6,1.0,48,Villa,Fully Furnished,Ready to Move,Urban,2/10/2024,11:14:00
3,4,1000.9,2.0,2,12.0,6,1.0,52,Apartment,Semi-Furnished,Ready to Move,Suburban,2/28/2024,12:21:00
4,5,1050.0,2.0,2,10.0,6,1.0,55,Independent House,Unfurnished,Under Construction,Urban,3/17/2024,13:28:00
5,6,1100.0,2.0,2,8.0,7,0.0,60,Apartment,Unfurnished,Ready to Move,Urban,4/4/2024,14:35:00
6,7,1150.5,NaN,2,7.0,Null,1.0,64,Independent House,Semi-Furnished,Under Construction,Suburban,4/22/2024,15:42:00
7,8,1200.0,3.0,2,6.0,7,1.0,68,Villa,Fully Furnished,Ready to Move,Urban,5/10/2024,16:49:00
8,9,1250.0,3.0,2,5.0,8,2.0,72,Apartment,Semi-Furnished,Ready to Move,Suburban,5/28/2024,17:56:00
9,10,1300.0,3.0,2,4.0,8,2.0,76,Independent House,Unfurnished,Under Construction,Urban,6/15/2024,9:03:00
10,11,1350.0,3.0,2,NaN,6,1.0,62,Apartment,Unfurnished,Ready to Move,Urban,7/3/2024,10:10:00
11,12,1400.0,3.0,2,10.0,7,2.0,67,Independent House,Semi-Furnished,Under Construction,Suburban,7/21/2024,11:17:00
12,13,1450.0,3.0,2,8.0,7,2.0,72,Villa,Fully Furnished,Ready to Move,Urban,8/8/2024,12:24:00
13,14,1500.0,3.0,2,6.0,8,2.0,78,Apartment,Semi-Furnished,Ready to Move,Suburban,8/26/2024,13:31:00
14,15,1550.0,3.0,2,5.0,8,2.0,83,Independent House,Unfurnished,Under Construction,Urban,9/13/2024,14:38:00
15,16,1600.0,3.0,0,4.0,8,2.0,88,Apartment,Unfurnished,Ready to Move,Urban,10/1/2024,15:45:00
16,17,1650.0,3.0,3,3.0,9,2.0,96,Independent House,Semi-Furnished,Under Construction,Suburban,10/19/2024,16:52:00
17,18,1700.0,3.0,3,2.0,9,2.0,102,Villa,Fully Furnished,Ready to Move,Urban,11/6/2024,17:59:00
18,19,1750.0,3.0,3,1.0,9,2.0,110,Apartment,Semi-Furnished,Ready to Move,Suburban,11/24/2024,9:06:00
19,20,1800.0,NaN,3,8.0,7,2.0,92,Independent House,Unfurnished,Under Construction,Urban,12/12/2024,10:13:00
20,21,1850.0,3.0,3,7.0,8,2.0,98,Apartment,Unfurnished,Ready to Move,Urban,12/30/2024,11:20:00
21,22,1900.0,3.0,3,6.0,8,2.0,105,Independent House,Semi-Furnished,Under Construction,Suburban,1/17/2025,12:27:00
22,23,1950.0,3.0,3,5.0,9,2.0,112,Villa,Fully Furnished,Ready to Move,Urban,2/4/2025,13:34:00
23,24,2000.0,4.0,3,4.0,9,2.0,125,Apartment,Semi-Furnished,Ready to Move,Suburban,2/22/2025,14:41:00
24,25,2050.0,4.0,3,3.0,9,2.0,132,Independent House,Unfurnished,Under Construction,Urban,3/12/2025,15:48:00
25,26,2100.0,4.0,3,2.0,10,2.0,140,Apartment,Unfurnished,Ready to Move,Urban,3/30/2025,16:55:00
26,27,2150.0,4.0,3,10.0,7,2.0,118,Independent House,Semi-Furnished,Under Construction,Suburban,4/17/2025,17:02:00
27,28,2200.0,4.0,3,9.0,8,2.0,126,Villa,Fully Furnished,Ready to Move,Urban,5/5/2025,9:09:00
28,29,2250.0,4.0,3,8.0,8,2.0,134,Apartment,Semi-Furnished,Ready to Move,Suburban,5/23/2025,10:16:00
29,30,2300.0,4.0,3,7.0,9,2.0,143,Independent House,Unfurnished,Under Construction,Urban,6/10/2025,11:23:00
30,31,2350.0,4.0,3,6.0,9,2.0,151,Apartment,Unfurnished,Ready to Move,Urban,6/28/2025,12:30:00
31,32,2400.0,4.0,3,5.0,9,2.0,160,Independent House,Semi-Furnished,Under Construction,Suburban,7/16/2025,13:37:00
32,33,2450.0,4.0,-3,4.0,10,2.0,170,Villa,Fully Furnished,Ready to Move,Urban,8/3/2025,14:44:00
33,34,2500.0,4.0,3,3.0,10,2.0,180,Apartment,Semi-Furnished,Ready to Move,Suburban,8/21/2025,15:51:00
34,35,2550.0,4.0,3,2.0,10,2.0,190,Independent House,Unfurnished,Under Construction,Urban,9/8/2025,16:58:00
35,36,2600.0,4.0,3,1.0,10,2.0,202,Apartment,Unfurnished,Ready to Move,Urban,9/26/2025,17:05:00
36,37,2650.0,4.0,3,15.0,6,2.0,145,Independent House,Semi-Furnished,Under Construction,Suburban,10/14/2025,9:12:00
37,38,2700.0,4.0,3,12.0,-7,2.0,155,Villa,Fully Furnished,Ready to Move,Urban,11/1/2025,10:19:00
38,39,2750.0,4.0,3,10.0,8,2.0,166,Apartment,Semi-Furnished,Ready to Move,Suburban,11/19/2025,11:26:00
39,40,2800.0,4.0,3,8.0,8,2.0,178,Independent House,Unfurnished,Under Construction,Urban,12/7/2025,12:33:00
40,41,2850.0,4.0,3,6.0,9,2.0,190,Apartment,Unfurnished,Ready to Move,Urban,12/25/2025,13:40:00
41,42,2900.0,4.0,3,5.0,9,2.0,203,Independent House,Semi-Furnished,Under Construction,Suburban,1/12/2026,14:47:00
42,43,2950.0,4.0,4,4.0,10,2.0,218,Villa,Fully Furnished,Ready to Move,Urban,1/30/2026,15:54:00
43,44,3000.0,4.0,4,3.0,10,2.0,232,Apartment,Semi-Furnished,Ready to Move,Suburban,2/17/2026,16:01:00
44,45,3100.0,4.0,4,2.0,10,3.0,-250,Independent House,Unfurnished,Under Construction,Urban,3/7/2026,17:08:00
45,46,3200.0,4.0,4,1.0,10,3.0,270,Apartment,Unfurnished,Ready to Move,Urban,3/25/2026,9:15:00
46,47,3300.0,5.0,4,7.0,9,3.0,285,Independent House,Semi-Furnished,Under Construction,Suburban,4/12/2026,10:22:00
47,48,3400.0,5.0,4,5.0,9,3.0,305,Villa,Fully Furnished,Ready to Move,Urban,4/30/2026,11:29:00
48,49,3500.0,5.0,4,3.0,10,3.0,330,Apartment,Semi-Furnished,Ready to Move,Suburban,5/18/2026,12:36:00
49,50,3600.0,5.0,4,1.0,10,3.0,355,Independent House,Unfurnished,Under Construction,Urban,6/5/2026,13:43:00
50,51,2750.0,4.0,3,10.0,8,2.0,166,Apartment,Semi-Furnished,Ready to Move,Suburban,11/19/2025,11:26:00
51,52,2250.0,4.0,3,8.0,8,2.0,134,Apartment,Semi-Furnished,Ready to Move,Suburban,5/23/2025,10:16:00

In [31]:
valid_furnishing = [
    "Unfurnished",
    "Semi-Furnished",
    "Fully Furnished"
]

data[
    ~data["Furnishing_Status"].isin(valid_furnishing)
]

Empty DataFrame
Columns: [House_ ID, Area_sqft, Bedrooms, Bathrooms, Age_years, Location_Score, Parking_Spaces, Price_lakhs, Property_Type, Furnishing_Status, Construction_Status, Locality_Type, Listing_Date, Listing_Time]
Index: []

## 9. Invalid Dates

### Step 1 – Understand the Concept
Own Words;  A date is invalid if it doesn't follow the expected date format or represents an impossible date.

Definition; Invalid dates cannot be correctly interpreted as calendar dates.

### Step 2 – Real-World Analogy

These are invalid:

2024-15-45 
2024-02-31 
ABC        

### Step 3 – Implement in Python
Check current type

In [32]:
data_clean.head()

,House_ ID,Area_sqft,Bedrooms,Bathrooms,Age_years,Location_Score,Parking_Spaces,Price_lakhs,Property_Type,Furnishing_Status,Construction_Status,Locality_Type,Listing_Date,Listing_Time
0,1,850.0,4.0,1,20.5,5.0,1.0,42.0,Apartment,Unfurnished,Ready to Move,Urban,1/5/2024,9:00:00
1,2,900.0,2.0,1,18.0,5.0,2.0,45.0,Independent House,Semi-Furnished,Under Construction,Suburban,1/23/2024,10:07:00
2,3,2150.0,2.0,1,15.0,6.0,1.0,48.0,Villa,Fully Furnished,Ready to Move,Urban,2/10/2024,11:14:00
3,4,1000.9,2.0,2,12.0,6.0,1.0,52.0,Apartment,Semi-Furnished,Ready to Move,Suburban,2/28/2024,12:21:00
4,5,1050.0,2.0,2,10.0,6.0,1.0,55.0,Independent House,Unfurnished,Under Construction,Urban,3/17/2024,13:28:00

In [33]:
##duplicates
data_clean.duplicated().sum()

np.int64(0)

In [34]:
duplicate_columns = [
    "Area_sqft",
    "Bedrooms",
    "Bathrooms",
    "Age_years",
    "Location_Score",
    "Parking_Spaces",
    "Price_lakhs",
    "Property_Type",
    "Furnishing_Status",
    "Construction_Status",
    "Locality_Type",
    "Listing_Date",
    "Listing_Time"
]

data_clean = data_clean.drop_duplicates(
    subset=duplicate_columns,
    keep="first"
)

In [35]:
data_clean.head(53)

,House_ ID,Area_sqft,Bedrooms,Bathrooms,Age_years,Location_Score,Parking_Spaces,Price_lakhs,Property_Type,Furnishing_Status,Construction_Status,Locality_Type,Listing_Date,Listing_Time
0,1,850.0,4.0,1,20.5,5.0,1.0,42.0,Apartment,Unfurnished,Ready to Move,Urban,1/5/2024,9:00:00
1,2,900.0,2.0,1,18.0,5.0,2.0,45.0,Independent House,Semi-Furnished,Under Construction,Suburban,1/23/2024,10:07:00
2,3,2150.0,2.0,1,15.0,6.0,1.0,48.0,Villa,Fully Furnished,Ready to Move,Urban,2/10/2024,11:14:00
3,4,1000.9,2.0,2,12.0,6.0,1.0,52.0,Apartment,Semi-Furnished,Ready to Move,Suburban,2/28/2024,12:21:00
4,5,1050.0,2.0,2,10.0,6.0,1.0,55.0,Independent House,Unfurnished,Under Construction,Urban,3/17/2024,13:28:00
5,6,1100.0,2.0,2,8.0,7.0,NaN,60.0,Apartment,Unfurnished,Ready to Move,Urban,4/4/2024,14:35:00
6,7,1150.5,4.0,2,7.0,8.0,1.0,64.0,Independent House,Semi-Furnished,Under Construction,Suburban,4/22/2024,15:42:00
7,8,1200.0,3.0,2,6.0,7.0,1.0,68.0,Villa,Fully Furnished,Ready to Move,Urban,5/10/2024,16:49:00
8,9,1250.0,3.0,2,5.0,8.0,2.0,72.0,Apartment,Semi-Furnished,Ready to Move,Suburban,5/28/2024,17:56:00
9,10,1300.0,3.0,2,4.0,8.0,2.0,76.0,Independent House,Unfurnished,Under Construction,Urban,6/15/2024,9:03:00
10,11,1350.0,3.0,2,6.0,6.0,1.0,62.0,Apartment,Unfurnished,Ready to Move,Urban,7/3/2024,10:10:00
11,12,1400.0,3.0,2,10.0,7.0,2.0,67.0,Independent House,Semi-Furnished,Under Construction,Suburban,7/21/2024,11:17:00
12,13,1450.0,3.0,2,8.0,7.0,2.0,72.0,Villa,Fully Furnished,Ready to Move,Urban,8/8/2024,12:24:00
13,14,1500.0,3.0,2,6.0,8.0,2.0,78.0,Apartment,Semi-Furnished,Ready to Move,Suburban,8/26/2024,13:31:00
14,15,1550.0,3.0,2,5.0,8.0,2.0,83.0,Independent House,Unfurnished,Under Construction,Urban,9/13/2024,14:38:00
15,16,1600.0,3.0,0,4.0,8.0,2.0,88.0,Apartment,Unfurnished,Ready to Move,Urban,10/1/2024,15:45:00
16,17,1650.0,3.0,3,3.0,9.0,2.0,96.0,Independent House,Semi-Furnished,Under Construction,Suburban,10/19/2024,16:52:00
17,18,1700.0,3.0,3,2.0,9.0,2.0,102.0,Villa,Fully Furnished,Ready to Move,Urban,11/6/2024,17:59:00
18,19,1750.0,3.0,3,1.0,9.0,2.0,110.0,Apartment,Semi-Furnished,Ready to Move,Suburban,11/24/2024,9:06:00
19,20,1800.0,4.0,3,8.0,7.0,2.0,92.0,Independent House,Unfurnished,Under Construction,Urban,12/12/2024,10:13:00
20,21,1850.0,3.0,3,7.0,8.0,2.0,98.0,Apartment,Unfurnished,Ready to Move,Urban,12/30/2024,11:20:00
21,22,1900.0,3.0,3,6.0,8.0,2.0,105.0,Independent House,Semi-Furnished,Under Construction,Suburban,1/17/2025,12:27:00
22,23,1950.0,3.0,3,5.0,9.0,2.0,112.0,Villa,Fully Furnished,Ready to Move,Urban,2/4/2025,13:34:00
23,24,2000.0,4.0,3,4.0,9.0,2.0,125.0,Apartment,Semi-Furnished,Ready to Move,Suburban,2/22/2025,14:41:00
24,25,2050.0,4.0,3,3.0,9.0,2.0,132.0,Independent House,Unfurnished,Under Construction,Urban,3/12/2025,15:48:00
25,26,2100.0,4.0,3,2.0,10.0,2.0,140.0,Apartment,Unfurnished,Ready to Move,Urban,3/30/2025,16:55:00
26,27,2150.0,4.0,3,10.0,7.0,2.0,118.0,Independent House,Semi-Furnished,Under Construction,Suburban,4/17/2025,17:02:00
27,28,2200.0,4.0,3,9.0,8.0,2.0,126.0,Villa,Fully Furnished,Ready to Move,Urban,5/5/2025,9:09:00
28,29,2250.0,4.0,3,8.0,8.0,2.0,134.0,Apartment,Semi-Furnished,Ready to Move,Suburban,5/23/2025,10:16:00
29,30,2300.0,4.0,3,7.0,9.0,2.0,143.0,Independent House,Unfurnished,Under Construction,Urban,6/10/2025,11:23:00
30,31,2350.0,4.0,3,6.0,9.0,2.0,151.0,Apartment,Unfurnished,Ready to Move,Urban,6/28/2025,12:30:00
31,32,2400.0,4.0,3,5.0,9.0,2.0,160.0,Independent House,Semi-Furnished,Under Construction,Suburban,7/16/2025,13:37:00
32,33,2450.0,4.0,-3,4.0,10.0,2.0,170.0,Villa,Fully Furnished,Ready to Move,Urban,8/3/2025,14:44:00
33,34,2500.0,4.0,3,3.0,10.0,2.0,180.0,Apartment,Semi-Furnished,Ready to Move,Suburban,8/21/2025,15:51:00
34,35,2550.0,4.0,3,2.0,10.0,2.0,190.0,Independent House,Unfurnished,Under Construction,Urban,9/8/2025,16:58:00
35,36,2600.0,4.0,3,1.0,10.0,2.0,202.0,Apartment,Unfurnished,Ready to Move,Urban,9/26/2025,17:05:00
36,37,2650.0,4.0,3,15.0,6.0,2.0,145.0,Independent House,Semi-Furnished,Under Construction,Suburban,10/14/2025,9:12:00
37,38,2700.0,4.0,3,12.0,8.0,2.0,155.0,Villa,Fully Furnished,Ready to Move,Urban,11/1/2025,10:19:00
38,39,2750.0,4.0,3,10.0,8.0,2.0,166.0,Apartment,Semi-Furnished,Ready to Move,Suburban,11/19/2025,11:26:00
39,40,2800.0,4.0,3,8.0,8.0,2.0,178.0,Independent House,Unfurnished,Under Construction,Urban,12/7/2025,12:33:00
40,41,2850.0,4.0,3,6.0,9.0,2.0,190.0,Apartment,Unfurnished,Ready to Move,Urban,12/25/2025,13:40:00
41,42,2900.0,4.0,3,5.0,9.0,2.0,203.0,Independent House,Semi-Furnished,Under Construction,Suburban,1/12/2026,14:47:00
42,43,2950.0,4.0,4,4.0,10.0,2.0,218.0,Villa,Fully Furnished,Ready to Move,Urban,1/30/2026,15:54:00
43,44,3000.0,4.0,4,3.0,10.0,2.0,232.0,Apartment,Semi-Furnished,Ready to Move,Suburban,2/17/2026,16:01:00
44,45,3100.0,4.0,4,2.0,10.0,3.0,NaN,Independent House,Unfurnished,Under Construction,Urban,3/7/2026,17:08:00
45,46,3200.0,4.0,4,1.0,10.0,3.0,270.0,Apartment,Unfurnished,Ready to Move,Urban,3/25/2026,9:15:00
46,47,3300.0,5.0,4,7.0,9.0,3.0,285.0,Independent House,Semi-Furnished,Under Construction,Suburban,4/12/2026,10:22:00
47,48,3400.0,5.0,4,5.0,9.0,3.0,305.0,Villa,Fully Furnished,Ready to Move,Urban,4/30/2026,11:29:00
48,49,3500.0,5.0,4,3.0,10.0,3.0,330.0,Apartment,Semi-Furnished,Ready to Move,Suburban,5/18/2026,12:36:00
49,50,3600.0,5.0,4,1.0,10.0,3.0,355.0,Independent House,Unfurnished,Under Construction,Urban,6/5/2026,13:43:00

In [36]:
print("Rows after removing duplicates:", len(data_clean))

Rows after removing duplicates: 50

In [45]:
data_clean.head()

,House_ ID,Area_sqft,Bedrooms,Bathrooms,Age_years,Location_Score,Parking_Spaces,Price_lakhs,Property_Type,Furnishing_Status,Construction_Status,Locality_Type,Listing_Date,Listing_Time
0,1,850.0,4.0,1,20.5,5.0,1.0,42.0,Apartment,Unfurnished,Ready to Move,Urban,00:00:00,09:00:00
1,2,900.0,2.0,1,18.0,5.0,2.0,45.0,Independent House,Semi-Furnished,Under Construction,Suburban,00:00:00,10:07:00
2,3,2150.0,2.0,1,15.0,6.0,1.0,48.0,Villa,Fully Furnished,Ready to Move,Urban,00:00:00,11:14:00
3,4,1000.9,2.0,2,12.0,6.0,1.0,52.0,Apartment,Semi-Furnished,Ready to Move,Suburban,00:00:00,12:21:00
4,5,1050.0,2.0,2,10.0,6.0,1.0,55.0,Independent House,Unfurnished,Under Construction,Urban,00:00:00,13:28:00

In [37]:
data_clean["Listing_Time"] = pd.to_datetime(data_clean["Listing_Time"], errors="coerce").dt.time

C:\Users\new\AppData\Local\Temp\ipykernel_12076\3735830297.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data_clean["Listing_Time"] = pd.to_datetime(data_clean["Listing_Time"], errors="coerce").dt.time

In [40]:
data_clean["Listing_Date"] = pd.to_datetime(data_clean["Listing_Date"], errors="coerce").dt.time

In [47]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   House_ ID            50 non-null     int64
 1   Area_sqft            50 non-null     float64
 2   Bedrooms             50 non-null     float64
 3   Bathrooms            50 non-null     int64
 4   Age_years            50 non-null     float64
 5   Location_Score       50 non-null     float64
 6   Parking_Spaces       49 non-null     float64
 7   Price_lakhs          49 non-null     float64
 8   Property_Type        50 non-null     object
 9   Furnishing_Status    50 non-null     object
 10  Construction_Status  50 non-null     object
 11  Locality_Type        50 non-null     object
 12  Listing_Date         50 non-null     object
 13  Listing_Time         50 non-null     object
dtypes: float64(6), int64(2), object(6)
memory usage: 5.9+ KB

In [49]:
data_clean = data_clean.drop(columns=["Listing_Date", "Listing_Time"])

In [50]:
data_clean.to_csv("house_price_prediction_cleaned.csv", index = False)

In [56]:
data_clean.head(53)

,House_ ID,Area_sqft,Bedrooms,Bathrooms,Age_years,Location_Score,Parking_Spaces,Price_lakhs,Property_Type,Furnishing_Status,Construction_Status,Locality_Type
0,1,850.0,4.0,1.0,20.5,5.0,1.0,42.0,Apartment,Unfurnished,Ready to Move,Urban
1,2,900.0,2.0,1.0,18.0,5.0,2.0,45.0,Independent House,Semi-Furnished,Under Construction,Suburban
2,3,2150.0,2.0,1.0,15.0,6.0,1.0,48.0,Villa,Fully Furnished,Ready to Move,Urban
3,4,1000.9,2.0,2.0,12.0,6.0,1.0,52.0,Apartment,Semi-Furnished,Ready to Move,Suburban
4,5,1050.0,2.0,2.0,10.0,6.0,1.0,55.0,Independent House,Unfurnished,Under Construction,Urban
5,6,1100.0,2.0,2.0,8.0,7.0,2.0,60.0,Apartment,Unfurnished,Ready to Move,Urban
6,7,1150.5,4.0,2.0,7.0,8.0,1.0,64.0,Independent House,Semi-Furnished,Under Construction,Suburban
7,8,1200.0,3.0,2.0,6.0,7.0,1.0,68.0,Villa,Fully Furnished,Ready to Move,Urban
8,9,1250.0,3.0,2.0,5.0,8.0,2.0,72.0,Apartment,Semi-Furnished,Ready to Move,Suburban
9,10,1300.0,3.0,2.0,4.0,8.0,2.0,76.0,Independent House,Unfurnished,Under Construction,Urban
10,11,1350.0,3.0,2.0,6.0,6.0,1.0,62.0,Apartment,Unfurnished,Ready to Move,Urban
11,12,1400.0,3.0,2.0,10.0,7.0,2.0,67.0,Independent House,Semi-Furnished,Under Construction,Suburban
12,13,1450.0,3.0,2.0,8.0,7.0,2.0,72.0,Villa,Fully Furnished,Ready to Move,Urban
13,14,1500.0,3.0,2.0,6.0,8.0,2.0,78.0,Apartment,Semi-Furnished,Ready to Move,Suburban
14,15,1550.0,3.0,2.0,5.0,8.0,2.0,83.0,Independent House,Unfurnished,Under Construction,Urban
15,16,1600.0,3.0,3.0,4.0,8.0,2.0,88.0,Apartment,Unfurnished,Ready to Move,Urban
16,17,1650.0,3.0,3.0,3.0,9.0,2.0,96.0,Independent House,Semi-Furnished,Under Construction,Suburban
17,18,1700.0,3.0,3.0,2.0,9.0,2.0,102.0,Villa,Fully Furnished,Ready to Move,Urban
18,19,1750.0,3.0,3.0,1.0,9.0,2.0,110.0,Apartment,Semi-Furnished,Ready to Move,Suburban
19,20,1800.0,4.0,3.0,8.0,7.0,2.0,92.0,Independent House,Unfurnished,Under Construction,Urban
20,21,1850.0,3.0,3.0,7.0,8.0,2.0,98.0,Apartment,Unfurnished,Ready to Move,Urban
21,22,1900.0,3.0,3.0,6.0,8.0,2.0,105.0,Independent House,Semi-Furnished,Under Construction,Suburban
22,23,1950.0,3.0,3.0,5.0,9.0,2.0,112.0,Villa,Fully Furnished,Ready to Move,Urban
23,24,2000.0,4.0,3.0,4.0,9.0,2.0,125.0,Apartment,Semi-Furnished,Ready to Move,Suburban
24,25,2050.0,4.0,3.0,3.0,9.0,2.0,132.0,Independent House,Unfurnished,Under Construction,Urban
25,26,2100.0,4.0,3.0,2.0,10.0,2.0,140.0,Apartment,Unfurnished,Ready to Move,Urban
26,27,2150.0,4.0,3.0,10.0,7.0,2.0,118.0,Independent House,Semi-Furnished,Under Construction,Suburban
27,28,2200.0,4.0,3.0,9.0,8.0,2.0,126.0,Villa,Fully Furnished,Ready to Move,Urban
28,29,2250.0,4.0,3.0,8.0,8.0,2.0,134.0,Apartment,Semi-Furnished,Ready to Move,Suburban
29,30,2300.0,4.0,3.0,7.0,9.0,2.0,143.0,Independent House,Unfurnished,Under Construction,Urban
30,31,2350.0,4.0,3.0,6.0,9.0,2.0,151.0,Apartment,Unfurnished,Ready to Move,Urban
31,32,2400.0,4.0,3.0,5.0,9.0,2.0,160.0,Independent House,Semi-Furnished,Under Construction,Suburban
32,33,2450.0,4.0,3.0,4.0,10.0,2.0,170.0,Villa,Fully Furnished,Ready to Move,Urban
33,34,2500.0,4.0,3.0,3.0,10.0,2.0,180.0,Apartment,Semi-Furnished,Ready to Move,Suburban
34,35,2550.0,4.0,3.0,2.0,10.0,2.0,190.0,Independent House,Unfurnished,Under Construction,Urban
35,36,2600.0,4.0,3.0,1.0,10.0,2.0,202.0,Apartment,Unfurnished,Ready to Move,Urban
36,37,2650.0,4.0,3.0,15.0,6.0,2.0,145.0,Independent House,Semi-Furnished,Under Construction,Suburban
37,38,2700.0,4.0,3.0,12.0,8.0,2.0,155.0,Villa,Fully Furnished,Ready to Move,Urban
38,39,2750.0,4.0,3.0,10.0,8.0,2.0,166.0,Apartment,Semi-Furnished,Ready to Move,Suburban
39,40,2800.0,4.0,3.0,8.0,8.0,2.0,178.0,Independent House,Unfurnished,Under Construction,Urban
40,41,2850.0,4.0,3.0,6.0,9.0,2.0,190.0,Apartment,Unfurnished,Ready to Move,Urban
41,42,2900.0,4.0,3.0,5.0,9.0,2.0,203.0,Independent House,Semi-Furnished,Under Construction,Suburban
42,43,2950.0,4.0,4.0,4.0,10.0,2.0,218.0,Villa,Fully Furnished,Ready to Move,Urban
43,44,3000.0,4.0,4.0,3.0,10.0,2.0,232.0,Apartment,Semi-Furnished,Ready to Move,Suburban
44,45,3100.0,4.0,4.0,2.0,10.0,3.0,125.0,Independent House,Unfurnished,Under Construction,Urban
45,46,3200.0,4.0,4.0,1.0,10.0,3.0,270.0,Apartment,Unfurnished,Ready to Move,Urban
46,47,3300.0,5.0,4.0,7.0,9.0,3.0,285.0,Independent House,Semi-Furnished,Under Construction,Suburban
47,48,3400.0,5.0,4.0,5.0,9.0,3.0,305.0,Villa,Fully Furnished,Ready to Move,Urban
48,49,3500.0,5.0,4.0,3.0,10.0,3.0,330.0,Apartment,Semi-Furnished,Ready to Move,Suburban
49,50,3600.0,5.0,4.0,1.0,10.0,3.0,355.0,Independent House,Unfurnished,Under Construction,Urban